export {
  BROADCAST_MESSAGE,
  type BroadcastChannelAdapterConfig,
  type BroadcastMessageType,
  broadcastChannelAdapterFactory,
  createBroadcastChannelAdapter,
} from "./adapters/broadcast-channel";
export {
  createNoopAdapter,
  type NoopAdapterConfig,
  noopAdapterFactory,
} from "./adapters/noop";
export type {
  AdapterConfig,
  AdapterConnectionState,
  AdapterFactory,
  AdapterUserInfo,
  PresenceAdapter,
  ReconnectConfig,
} from "./adapters/types";
export {
  createWebSocketAdapter,
  type WebSocketAdapterConfig,
  webSocketAdapterFactory,
} from "./adapters/websocket";
// Shared attention: session identity, invitations, follow relationships and
// the version-3 capability handshake. Also available as
// `@softmaple/awareness/attention` for consumers that only need the contracts.
export * from "./attention";
export {
  ActivityIndicator,
  type ActivityIndicatorProps,
  BlockActivityIndicator,
  type BlockActivityIndicatorProps,
  CollaborationBar,
  type CollaborationBarProps,
  ConnectionIndicator,
  type ConnectionIndicatorLabels,
  type ConnectionIndicatorProps,
  formatPresenceSummary,
  formatRelativeTime,
  getInitials,
  type HighlightRect,
  LiveCursor,
  type LiveCursorPoint,
  type LiveCursorProps,
  type LiveCursorViewport,
  PresenceAvatar,
  type PresenceAvatarProps,
  type PresenceAvatarSize,
  PresenceBar,
  type PresenceBarProps,
  PresenceLayer,
  type PresenceLayerOffset,
  type PresenceLayerProps,
  SelectionHighlight,
  type SelectionHighlightProps,
  usePresenceLayerOffset,
} from "./components";
export {
  createPresenceStore,
  createSelfSession,
  derivePresenceStatus,
  isUserIdle,
  isUserOffline,
  PRESENCE_CAPABILITIES,
  PRESENCE_PROTOCOL_VERSION,
  type PresenceCapability,
  type PresenceHello,
  type PresenceStore,
  type PresenceStoreListener,
  type PresenceStoreOptions,
  type StatusTimeouts,
  sweepPresenceStatuses,
  withDerivedStatus,
} from "./core";
export {
  mapTextareaSelectionThroughOperation,
  type PeerCursor,
  type TextareaSelection,
  type TextareaSelectionDirection,
  type UsePeerCursorsOptions,
  type UsePeersInBlockOptions,
  type UseTextareaSelectionSyncResult,
  useActivityByType,
  useConnectionState,
  useIsConnected,
  useOther,
  useOthers,
  useOthersCount,
  useOthersFiltered,
  usePeerCursors,
  usePeersInBlock,
  usePresence,
  useRecentActivity,
  useSelf,
  useSelfSelector,
  useTextareaSelectionSync,
  useUpdateCursor,
  useUpdatePresence,
  useUpdateSelection,
  useUpdateTyping,
  useUserActivity,
} from "./hooks";
export {
  PresenceContext,
  type PresenceContextValue,
  PresenceProvider,
  type PresenceProviderProps,
} from "./providers";
export {
  createInitialPresenceState,
  getOnlineUsers,
  getOtherUsers,
  getSelfUser,
  getUserById,
  getUsersArray,
} from "./state/selectors";
export {
  ACTIVITY_TYPE,
  type ActivityEvent,
  type ActivityEventData,
  type ActivityType,
  type CursorEventData,
  type IdleEventData,
  type JoinEventData,
  type LeaveEventData,
  PRESENCE_EVENT,
  type PresenceEvent,
  type PresenceEventPayload,
  type PresenceEventType,
  type PresenceJoinPayload,
  type PresenceLeavePayload,
  type PresenceSyncPayload,
  type PresenceUpdatePayload,
  type PresenceUserUpdates,
  type SelectionEventData,
  type TypingEventData,
} from "./types/events";
export {
  type AtomSequenceAnchor,
  applyClockedPresenceUpdate,
  type BlockSelectionPoint,
  type BoundarySequenceAnchor,
  type CreatePresenceUserOptions,
  type CursorPosition,
  createConnectionId,
  createPresenceUser,
  type DirectionalSelectionRange,
  type EndBoundarySequenceAnchor,
  getCursorOffset,
  isCursorPosition,
  isDirectionalSelectionRange,
  isLegacySelectionRange,
  isOffsetCursorPosition,
  isPresenceSelection,
  isSequenceAnchor,
  isStableCursor,
  isStableCursorPosition,
  markUserActivity,
  normalizeCursorPosition,
  normalizePresenceSelection,
  type OffsetCursorPosition,
  type PresenceMeta,
  type PresenceSelection,
  type PresenceStatus,
  type PresenceUser,
  type PresenceUserPatch,
  patchPresenceUser,
  type SelectionRange,
  type SelfPresence,
  type SequenceAnchor,
  type SequenceAnchorAffinity,
  type StableCursorPosition,
  type StartBoundarySequenceAnchor,
  selectionReferencesBlock,
  touchUserSeen,
  updatePresenceUser,
} from "./types/presence";
export type {
  ConnectionStatus,
  PresenceState,
  PresenceStateConfig,
} from "./types/state";
export { DEFAULT_PRESENCE_CONFIG } from "./types/state";
export type {
  SurfaceBinding,
  SurfaceBindingSubscription,
  SurfaceOperation,
  SurfaceSelection,
} from "./types/surface-binding";
export {
  getTextareaCaretRect,
  getTextareaSelectionRects,
  type TextareaCaretRect,
  type TextareaSelectionRange,
} from "./utils/textarea-rects";
