export {
  BROADCAST_MESSAGE,
  type BroadcastChannelAdapterConfig,
  type BroadcastMessageType,
  broadcastChannelAdapterFactory,
  createBroadcastChannelAdapter,
} from "./adapters/broadcast-channel";
export {
  createNoopAdapter,
  type NoopAdapterConfig,
  noopAdapterFactory,
} from "./adapters/noop";
export type {
  AdapterConfig,
  AdapterConnectionState,
  AdapterFactory,
  AdapterUserInfo,
  PresenceAdapter,
  ReconnectConfig,
} from "./adapters/types";
export {
  createWebSocketAdapter,
  type WebSocketAdapterConfig,
  webSocketAdapterFactory,
} from "./adapters/websocket";
export {
  ActivityIndicator,
  type ActivityIndicatorProps,
  BlockActivityIndicator,
  type BlockActivityIndicatorProps,
  ConnectionIndicator,
  type ConnectionIndicatorLabels,
  type ConnectionIndicatorProps,
  type HighlightRect,
  LiveCursor,
  type LiveCursorPoint,
  type LiveCursorProps,
  type LiveCursorViewport,
  PresenceAvatar,
  type PresenceAvatarProps,
  type PresenceAvatarSize,
  PresenceBar,
  type PresenceBarProps,
  PresenceLayer,
  type PresenceLayerOffset,
  type PresenceLayerProps,
  SelectionHighlight,
  type SelectionHighlightProps,
  usePresenceLayerOffset,
} from "./components";
export {
  type PeerCursor,
  type UsePeerCursorsOptions,
  type UsePeersInBlockOptions,
  useActivityByType,
  useConnectionState,
  useIsConnected,
  useOther,
  useOthers,
  useOthersCount,
  useOthersFiltered,
  usePeerCursors,
  usePeersInBlock,
  usePresence,
  useRecentActivity,
  useSelf,
  useSelfSelector,
  useUpdateCursor,
  useUpdatePresence,
  useUpdateSelection,
  useUpdateTyping,
  useUserActivity,
} from "./hooks";
export {
  PresenceContext,
  type PresenceContextValue,
  PresenceProvider,
  type PresenceProviderProps,
} from "./providers";
export {
  createInitialPresenceState,
  DEFAULT_PRESENCE_CONFIG,
  getOnlineUsers,
  getOtherUsers,
  getSelfUser,
  getUserById,
  getUsersArray,
} from "./state/selectors";
export {
  ACTIVITY_TYPE,
  type ActivityEvent,
  type ActivityEventData,
  type ActivityType,
  type CursorEventData,
  type IdleEventData,
  type JoinEventData,
  type LeaveEventData,
  PRESENCE_EVENT,
  type PresenceEvent,
  type PresenceEventPayload,
  type PresenceEventType,
  type PresenceJoinPayload,
  type PresenceLeavePayload,
  type PresenceSyncPayload,
  type PresenceUpdatePayload,
  type PresenceUserUpdates,
  type SelectionEventData,
  type TypingEventData,
} from "./types/events";
export {
  type CreatePresenceUserOptions,
  type CursorPosition,
  createPresenceUser,
  type PresenceMeta,
  type PresenceStatus,
  type PresenceUser,
  type SelectionRange,
  type SelfPresence,
  updatePresenceUser,
} from "./types/presence";
export type {
  ConnectionStatus,
  PresenceState,
  PresenceStateConfig,
} from "./types/state";
export {
  getTextareaCaretRect,
  getTextareaSelectionRects,
  type TextareaCaretRect,
  type TextareaSelectionRange,
} from "./utils/textarea-rects";
