export {
  ActivityIndicator,
  type ActivityIndicatorProps,
  type HighlightRect,
  LiveCursor,
  type LiveCursorPoint,
  type LiveCursorProps,
  PresenceAvatar,
  type PresenceAvatarProps,
  type PresenceAvatarSize,
  PresenceBar,
  type PresenceBarProps,
  SelectionHighlight,
  type SelectionHighlightProps,
} from "./components";
export { ACTIVITY_TYPE, PRESENCE_EVENT } from "./constants/presence-events";
export {
  useActivityByType,
  useAwareness,
  useConnectionState,
  useIsConnected,
  useOther,
  useOthers,
  useOthersCount,
  useOthersFiltered,
  usePresence,
  useRecentActivity,
  useSelf,
  useSelfSelector,
  useUpdateCursor,
  useUpdatePresence,
  useUpdateSelection,
  useUpdateTyping,
  useUserActivity,
} from "./hooks";
export {
  PresenceContext,
  type PresenceContextValue,
} from "./providers/presence-context";
export {
  PresenceProvider as AwarenessProvider,
  PresenceProvider,
  type PresenceProviderProps,
} from "./providers/presence-provider";
export type {
  ActivityEvent,
  ActivityEventData,
  ActivityType,
  CursorEventData,
  IdleEventData,
  JoinEventData,
  LeaveEventData,
  PresenceEvent,
  PresenceEventPayload,
  PresenceEventType,
  PresenceJoinPayload,
  PresenceLeavePayload,
  PresenceSyncPayload,
  PresenceUpdatePayload,
  PresenceUserUpdates,
  SelectionEventData,
  TypingEventData,
} from "./types/events";
export {
  type CreatePresenceUserOptions,
  type CursorPosition,
  createPresenceUser,
  type PresenceMeta,
  type PresenceStatus,
  type PresenceUser,
  type SelectionRange,
  type SelfPresence,
  updatePresenceUser,
} from "./types/presence";
export {
  type ConnectionStatus,
  createInitialPresenceState,
  DEFAULT_PRESENCE_CONFIG,
  getOnlineUsers,
  getOtherUsers,
  getSelfUser,
  getUserById,
  getUsersArray,
  type PresenceState,
  type PresenceStateConfig,
} from "./types/state";
