packages:
  - "docs"
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js-pure: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
