name: Test "@softmaple/md2latex" package

on:
  push:
    paths:
      - 'packages/md2latex/**/*.ts'
      - 'packages/md2latex/**/*.test.ts'
      - 'packages/md2latex/**/*.spec.ts'
      - 'packages/md2latex/package.json'
      - 'packages/md2latex/vitest.config.*'
  pull_request:
    paths:
      - 'packages/md2latex/**/*.ts'
      - 'packages/md2latex/**/*.test.ts'
      - 'packages/md2latex/**/*.spec.ts'
      - 'packages/md2latex/package.json'
      - 'packages/md2latex/vitest.config.*'

permissions:
  contents: read

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        working-directory: packages/md2latex
        run: pnpm test
